/**
 * More "Did you know?" facts for each animal, shown after its main fact in
 * animals.ts. Kept short, true and easy to picture for a four- to seven-year-old.
 * Add freely, but only facts you could show a source for.
 */
import type { Animal } from './animals';

export const FUN_FACTS: Record<string, string[]> = {
  dog: ['Every dog\'s nose print is different, just like your fingerprint.', 'Dogs cool down by panting with their tongues out.'],
  cat: ['A cat\'s whiskers help it feel its way in the dark.', 'Cats walk on their tiptoes.'],
  cow: ['A cow\'s tummy has four different parts.', 'Cows spend many hours every day eating grass.'],
  pig: ['Pigs are very clever and can learn their own names.', 'Pigs can sniff out food hidden under the ground.'],
  sheep: ['Sheep can remember the faces of other sheep.', 'A sheep\'s wool keeps growing until it is cut.'],
  horse: ['Horses have the biggest eyes of any animal that lives on land.', 'You can tell a horse\'s age by looking at its teeth.'],
  hen: ['Chickens are distant cousins of the dinosaurs.', 'A hen gently turns her eggs many times a day.'],
  rooster: ['The red crest on a rooster\'s head is called a comb.', 'Roosters crow at all times of day, not just in the morning.'],
  duck: ['A duck\'s feathers are waterproof, so it stays dry in the water.', 'Ducklings follow the first moving thing they see after hatching.'],
  goat: ['Goats have rectangle-shaped pupils in their eyes.', 'Baby goats can stand up just minutes after they are born.'],
  turkey: ['Wild turkeys can run fast and fly short distances.', 'The floppy red skin under a turkey\'s beak is called a wattle.'],
  rabbit: ['Rabbits can turn their ears to listen in different directions.', 'Happy rabbits jump and twist in the air. It is called a binky!'],
  mouse: ['Mice use their whiskers to feel where they are going.', 'A mouse can squeeze through a gap about as wide as a pencil.'],
  hamster: ['Hamsters are most awake at night.', 'A hamster\'s teeth never stop growing.'],
  buffalo: ['Water buffaloes help farmers pull ploughs in rice fields.', 'Water buffaloes have big curved horns.'],
  llama: ['Llamas hum to talk to each other.', 'Llamas help people carry heavy loads up mountains.'],
  camel: ['A camel\'s hump stores fat, not water.', 'Camels have long eyelashes that keep sand out of their eyes.'],
  lion: ['Lions live in family groups called prides.', 'Lions can sleep for most of the day.'],
  tiger: ['Tigers are the biggest cats in the world.', 'Unlike most cats, tigers love to swim.'],
  leopard: ['A leopard\'s spots are called rosettes.', 'Leopards like to hunt at night.'],
  elephant: ['Elephants are the biggest animals on land.', 'Elephants flap their big ears to cool down.'],
  giraffe: ['A giraffe\'s long tongue is a dark blue-purple colour.', 'Giraffes sleep only a little, in short naps.'],
  zebra: ['Zebras can sleep standing up.', 'A group of zebras is called a dazzle.'],
  rhino: ['Rhinos roll in mud to protect their skin from the sun.', 'Rhinos cannot see very well, but they smell and hear very well.'],
  hippo: ['Hippos cannot really swim. They walk and bounce along the bottom!', 'A hippo can hold its breath for about five minutes.'],
  monkey: ['Some monkeys use their tails to hold on to branches.', 'Monkeys clean each other\'s fur to stay neat and make friends.'],
  gorilla: ['Gorillas make a new leafy nest to sleep in every night.', 'Gorillas can use sticks as simple tools.'],
  orangutan: ['Orangutans have very long, strong arms.', 'Orangutans hold big leaves over their heads like umbrellas when it rains.'],
  bear: ['Bears have a super sense of smell.', 'Bears can stand up on their back legs to look around.'],
  panda: ['A newborn panda is tiny and pink.', 'Pandas have a special thumb-like bone that helps them hold bamboo.'],
  koala: ['Koalas sleep for most of the day.', 'Koalas are not bears. Like kangaroos, the mothers have pouches.'],
  kangaroo: ['Kangaroos hop on their strong back legs.', 'Kangaroos use their big tails to help them balance.'],
  fox: ['Foxes can hear tiny animals moving under the snow.', 'A fox\'s home under the ground is called a den.'],
  wolf: ['Wolves howl to talk to their pack.', 'Dogs and wolves are close relatives.'],
  deer: ['Deer can run fast and jump high.', 'A baby deer has white spots that help it hide.'],
  chipmunk: ['Chipmunks dig long tunnels under the ground.', 'Chipmunks have stripes down their backs.'],
  hedgehog: ['A hedgehog has thousands of spines.', 'Hedgehogs snuffle and snort while they hunt for bugs.'],
  bat: ['Many bats find their way in the dark by listening to echoes.', 'Bats sleep hanging upside down.'],
  raccoon: ['Raccoons have dark fur around their eyes, like a mask.', 'Raccoons often dip their food in water before eating it.'],
  skunk: ['Skunks stamp their feet as a warning before they spray.', 'Skunks have black and white stripes.'],
  sloth: ['Sloths climb down from their trees only about once a week.', 'Tiny green plants can grow in a sloth\'s fur.'],
  otter: ['Sea otters use rocks as tools to crack open shells.', 'Sea otters have the thickest fur of any animal.'],
  badger: ['Badgers have long, strong claws for digging.', 'Many badgers have stripes on their faces.'],
  crocodile: ['Crocodiles cannot stick out their tongues.', 'Crocodile mothers carry their babies gently in their mouths.'],
  snake: ['Snakes do not have eyelids.', 'Snakes wriggle out of their old skin as they grow.'],
  lizard: ['Some lizards can run on just their two back legs.', 'Geckos can climb walls with their sticky feet.'],
  turtle: ['Sea turtles lay their eggs in sandy beaches.', 'Some turtles live for more than 100 years.'],
  frog: ['Frogs drink water through their skin.', 'Some frogs can jump many times their own length.'],
  fish: ['Most fish lay eggs.', 'There were fish in the sea long before the dinosaurs.'],
  'tropical-fish': ['Clownfish live safely among stinging sea anemones.', 'Coral reefs are home to thousands of kinds of fish.'],
  pufferfish: ['Many pufferfish have spines that stick out when they puff up.', 'Some pufferfish draw beautiful patterns in the sand.'],
  shark: ['Sharks were swimming in the sea before the dinosaurs lived.', 'Sharks have no bones. Their skeletons are bendy, like your ears.'],
  whale: ['The blue whale is the biggest animal that has ever lived.', 'Some whales sing long songs to each other.'],
  dolphin: ['Dolphins rest one half of their brain at a time.', 'Each dolphin has its own special whistle, like a name.'],
  octopus: ['An octopus has three hearts.', 'An octopus can change colour to hide.'],
  squid: ['Squid have eight arms and two longer tentacles.', 'Giant squid can be longer than a bus.'],
  crab: ['Crabs have ten legs, and the front two are claws.', 'Hermit crabs move into bigger shells as they grow.'],
  lobster: ['A lobster can grow back a lost claw.', 'Most lobsters are greenish-brown, not red.'],
  shrimp: ['Some shrimp clean other fish by nibbling tiny bits off them.', 'A shrimp\'s heart is in its head.'],
  penguin: ['Emperor penguin dads keep the egg warm on their feet.', 'Penguins slide across the ice on their tummies.'],
  owl: ['Owls fly almost silently.', 'Owls cannot move their eyes, so they turn their heads instead.'],
  eagle: ['Eagles build huge nests high up in trees and on cliffs.', 'Eagles catch food with their sharp claws, called talons.'],
  parrot: ['Some parrots live for more than 60 years.', 'Parrots have two toes pointing forwards and two pointing backwards.'],
  swan: ['Swans often stay with the same partner for life.', 'Baby swans ride on their parents\' backs.'],
  peacock: ['Only the dad is called a peacock. The mum is a peahen.', 'Peacocks fly up into trees to sleep.'],
  flamingo: ['Flamingos often stand on one leg.', 'Flamingos eat with their heads upside down.'],
  dove: ['Doves and pigeons belong to the same bird family.', 'Doves drink by sucking up water, like through a straw.'],
  butterfly: ['Butterflies cannot fly when they are too cold.', 'Butterfly wings are covered in tiny scales.'],
  bee: ['Bees dance to show other bees where the flowers are.', 'A bee has five eyes.'],
  ladybug: ['A ladybug\'s bright colours warn birds: "I taste bad!"', 'Ladybugs can have lots of spots, or none at all.'],
  ant: ['Ants live together in big groups called colonies.', 'Ants talk to each other using smells.'],
  caterpillar: ['A caterpillar sheds its skin several times as it grows.', 'A caterpillar eats and eats before it changes into a butterfly or moth.'],
  snail: ['Snails make slime to help them slide along.', 'A land snail\'s eyes are on the tips of its tentacles.'],
  spider: ['Spider silk is very strong for its size.', 'Most spiders have eight eyes.'],
  cricket: ['A cricket\'s ears are on its front legs.', 'Crickets chirp faster when it is warm.'],
  mosquito: ['Mosquitoes find people by the air we breathe out.', 'A mosquito\'s wings beat hundreds of times every second.'],
  scorpion: ['Mother scorpions carry their babies on their backs.', 'Scorpions have lived on Earth for millions of years.'],
  't-rex': ['Some T. rex teeth were as big as bananas.', 'T. rex had tiny arms but a huge head.'],
  'long-neck': ['Some long-necked dinosaurs were longer than three buses.', 'Their long necks let them reach leaves that other animals could not.'],
};

/** Every fact for an animal: its main fact first, then the fun facts. */
export const factsFor = (animal: Animal) => [animal.fact, ...(FUN_FACTS[animal.key] ?? [])];
