import type { TraitKey } from './traits.js';

export interface AssessmentBlueprint {
  construct: string;
  evidence: string;
  taskPatterns: string[];
  avoid: string[];
}

const plan = (construct: string, evidence: string, taskPatterns: string[], avoid: string[]): AssessmentBlueprint => ({ construct, evidence, taskPatterns, avoid });

/** Private generation guidance. This is deliberately richer than the parent-facing category blurb. */
export const ASSESSMENT_BLUEPRINTS: Record<TraitKey, AssessmentBlueprint> = {
  abstract_concepts: plan('understanding non-physical rules, categories, relationships, or meanings', 'applies or explains an abstract idea in a new concrete example', ['analogy', 'which examples follow a rule', 'explain fairness, kindness, or belonging through a scenario'], ['simple fact recall', 'vocabulary-definition recall', 'visual detail alone']),
  beyond_experience: plan('reasoning about an unfamiliar but safe hypothetical situation', 'uses stated conditions to form a plausible idea beyond personal experience', ['imaginary place with clear rules', 'novel tool or creature', 'what would change in a fictional situation'], ['asking what happened to the child before', 'specialist knowledge', 'fantasy with no reasoning constraint']),
  generalization: plan('finding a rule from examples and applying it to a new case', 'states or correctly uses the shared rule on an unseen example', ['example sequence then new case', 'sort by a discovered rule', 'choose which new example belongs'], ['one-off matching', 'memorized facts', 'ambiguous multiple rules']),
  cause_effect: plan('connecting a change or event to a plausible consequence', 'identifies what caused an outcome or predicts what follows from one changed condition', ['before-and-after scenario', 'change one condition', 'simple mechanism prediction'], ['mere sequencing', 'moral judgment', 'multiple unstated causes']),
  challenge_seeking: plan('approach to choosing and engaging with manageable difficulty in this moment', 'selects or describes a strategy for trying a harder option while allowing help and breaks', ['easy-versus-tricky choice', 'first step on a puzzle', 'what to do when stuck'], ['claiming a stable preference', 'rewarding distress or refusal to seek help', 'equating speed with challenge']),
  curiosity: plan('going beyond given information with useful questions or possibilities', 'asks or selects a relevant how, why, or what-if question that extends the situation', ['choose the question that would teach more', 'invent a what-if', 'notice what remains unknown'], ['enthusiasm alone', 'answering a fact already given', 'rewarding question quantity without relevance']),
  original_methods: plan('finding a sound, less-obvious route to a goal', 'offers or recognizes a workable alternative method and connects it to the goal', ['two ways to solve', 'unusual use for familiar materials', 'finish a task under a new constraint'], ['novelty without usefulness', 'artistic preference alone', 'one prescribed method']),
  observant: plan('noticing relevant details, changes, and differences', 'identifies a subtle but clearly visible or stated detail needed for the answer', ['spot the meaningful difference', 'remember a short set of stated details', 'find the clue that changes the answer'], ['trivia', 'tiny emoji rendering differences', 'memory load unrelated to observation']),
  perfectionism: plan('balancing care, flexibility, mistakes, and completion', 'chooses a healthy next step after an imperfection while still valuing effort', ['minor mistake in a project', 'decide when work is ready', 'adapt when materials differ'], ['rewarding anxiety or rigidity', 'calling perfection good or bad', 'diagnosing a trait']),
  strong_ideas: plan('giving reasons for an opinion while recognizing another viewpoint', 'states a preference with a relevant reason and can consider a different reasonable view', ['two defensible choices', 'persuade kindly', 'compare viewpoints'], ['one morally correct opinion', 'agreement with adults', 'argumentativeness']),
  questions_authority: plan('asking respectful, safety-aware questions about rules and reasons', 'forms or chooses a clear question that seeks the reason for a rule', ['unclear everyday rule', 'request an explanation', 'suggest a respectful alternative'], ['rewarding obedience or defiance', 'unsafe rule-breaking', 'politics or adult institutions']),
  motivation_focus: plan('strategies for beginning, continuing, and returning to a chosen task', 'selects or explains a practical focus strategy under a specific distraction or setback', ['break a project into steps', 'return after interruption', 'prepare a workspace'], ['diagnosing attention', 'using duration as proof', 'rewarding overwork']),
  humor: plan('kind wordplay, incongruity, and playful reinterpretation', 'recognizes or creates an age-appropriate joke whose humor comes from meaning or sound', ['complete a gentle joke', 'choose a playful double meaning', 'invent a silly safe twist'], ['mocking a person', 'cultural references', 'random silliness with no link']),
  sensitivity_others: plan('noticing another person’s possible need and responding thoughtfully', 'uses scenario clues to suggest a helpful response while allowing more than one feeling', ['friend left out', 'someone needs practical help', 'ask before helping'], ['mind-reading', 'one mandatory emotion', 'moral labels or self-sacrifice']),
  extensive_vocabulary: plan('precise, appropriate word meaning in context', 'chooses or uses a word that makes an age-appropriate meaning more exact', ['choose the most precise familiar word', 'replace a vague word from context', 'describe a scene accurately'], ['obscure-word recall', 'penalizing simple correct language', 'spelling or grammar as the target']),
  advanced_reading: plan('comprehending and engaging with age-adjusted narrative language', 'uses details from a short spoken or readable passage to infer, predict, or connect ideas', ['short story inference', 'put story events together', 'predict from character actions'], ['claiming reading frequency or grade level', 'long passages', 'requiring reading for ages 4–5']),
  self_motivated_writing: plan('generating and organizing an original story, poem, journal, or message idea', 'creates a coherent original idea with a purpose; oral responses count fully', ['continue a story', 'invent a short message or poem idea', 'choose what to create and why'], ['requiring handwriting or typing', 'judging spelling', 'claiming lasting motivation']),
  viewpoint_mood_intention: plan('inferring viewpoint, mood, or intention from explicit contextual clues', 'identifies a plausible perspective or intention and points to a supplied clue', ['two characters see one event differently', 'tone or action reveals mood', 'why a speaker said something'], ['mind-reading without clues', 'single emotion stereotypes', 'advanced literary terminology']),
  advanced_spelling: plan('age-appropriate sound-letter and word-pattern knowledge', 'recognizes or produces a spelling pattern suitable for the exact age', ['match a spoken sound to a letter for pre-readers', 'choose between short word spellings', 'notice a word-family pattern'], ['printed-word tasks for ages 4–5', 'rare irregular words', 'scoring speech recognition errors as spelling errors']),
  how_things_work: plan('mechanistic curiosity about familiar systems', 'asks or answers a useful causal question about parts, actions, or processes', ['simple machine or household object', 'what part does what', 'which question would reveal the mechanism'], ['fact trivia', 'unsafe experiments', 'technical vocabulary']),
  mental_math: plan('age-appropriate quantitative relationships and flexible number reasoning', 'solves or compares a small quantity relationship using a sensible mental strategy', ['visible objects for ages 4–5', 'compose or decompose small numbers', 'compare quantities or simple patterns'], ['speed as evidence', 'written arithmetic for ages 4–5', 'grade labels or timed pressure']),
  strategy_games: plan('planning ahead under simple, fully stated rules', 'compares possible moves and chooses one that improves a stated goal', ['one- or two-move picture game', 'choose a move under a simple rule', 'anticipate another player’s next option'], ['assuming chess knowledge', 'unstated rules', 'chance presented as strategy']),
  categories_hierarchies: plan('grouping by attributes and understanding nested groups', 'sorts items by a relevant feature or recognizes how a smaller category fits a larger one', ['sort familiar objects', 'find a subgroup', 'explain two valid grouping rules'], ['arbitrary associations', 'one-off visual matching', 'specialist taxonomy']),
  intuitive_problem_solving: plan('arriving at a sound solution when full step-by-step explanation may be incomplete', 'gives a workable answer or prediction; explanation adds evidence but is not required for full correctness', ['pattern completion', 'spatial or practical puzzle', 'choose an answer then optionally describe the hunch'], ['requiring verbal justification for full credit', 'mystical intuition', 'ambiguous puzzles']),
};
